version: 2.1

orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@1.0.6

jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test:cov
          name: Run tests
      - coveralls/upload

workflows:
  test:
    jobs:
      - test